import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const open = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--open",
});

const fonts = open.variable;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fonts} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
